In [1]:
import numpy as np
import glob 
import cv2
import pandas as pd
from makiflow.augmentation.segmentation import HCScanner
import tensorflow as tf
from tqdm import tqdm
import os
from makiflow.augmentation import AffineAugment, ElasticAugment, ImageCutter, Data
from makiflow.tf_scripts import set_main_gpu
import glob
set_main_gpu(0)

In [ ]:
{1 : 16,
 2 : 14,
 3 : 16,
 4 : 5,
 5 : 10,
 6 : 7,
 7 : 2,
 8 : 3,
 9 : 14,
}

In [ ]:
def get_train_data(path='/mnt/data/med_data/all_data'):
    Xtrain, Ytrain = [], []
    masks = glob.glob(path + '/masks/*.bmp')
    masks.sort()
    for mask_name in tqdm(masks):
        img = cv2.imread(mask_name.replace('masks', 'images'))
        mask = cv2.imread(mask_name)
        Xtrain.append(img)
        Ytrain.append(mask[:,:,0])
        if np.max(mask) >= 10:
            print(np.max(mask), f' in image {mask_name} ')
    return Xtrain, Ytrain

In [ ]:
X,Y = get_train_data()

In [ ]:
def count(lbls, classes):
    uniq = dict([(str(i),0) for i in range(classes)])
    
    for i in range(len(lbls)):
        if i in batch_3:
            a,_ = np.unique(lbls[i], return_counts=True)
            for m in a:
                uniq[str(m)] += 1
            print(i,' have classes ', a)
    
    return uniq

In [ ]:
count(Y,10)

In [ ]:
batch_3 = [91,107,52,16,8,14,72,98,96,60,104,103,102,101,49,38]

In [ ]:
len(batch_3)

In [ ]:
batch_2 = [44,114,17,40,89,106,21,45,81,32,36,67,110,105,37,11]

In [ ]:
len(batch_2)

In [ ]:
batch_1 = [1,5,27,59,33,34,35,95,43,15,23,28,29,13,39,24]

In [ ]:
sorted(batch_3)

In [ ]:
def count(lbls, classes):
    uniq = dict([(str(i),0) for i in range(classes)])
    
    for i in range(len(lbls)):
        if i not in batch_1 and i not in batch_2:
            a,_ = np.unique(lbls[i], return_counts=True)
            for m in a:
                uniq[str(m)] += 1
            print(i,' have classes ', a)
    
    return uniq

count(Y,10)

In [ ]:
def save_imgs(imgs, masks,batch_test, path_to_save='/mnt/data/med_data/balanced_batches/batch_3/'):
    for i, (img, mask) in enumerate(zip(imgs, masks)):
        path_save_img = None
        path_save_mask = None
        if i in batch_test:
            path_save_img = path_to_save + 'test_set/images'
            path_save_mask = path_to_save + 'test_set/masks'
        else:
            path_save_img = path_to_save + 'train_set/origin_set/images'
            path_save_mask = path_to_save + 'train_set/origin_set/masks'
        cv2.imwrite(path_save_img+f'/{i}.bmp', mask)
        cv2.imwrite(path_save_mask + f'/{i}.bmp', img)

In [ ]:
save_imgs(X,Y,batch_3)

In [ ]:
import seaborn as sb
import matplotlib.pyplot as plt

In [ ]:
i = 3

In [ ]:
sb.heatmap(Y[i])

In [ ]:
a = sb.heatmap(Y[i])
b = a.get_figure()
b.savefig('test_mask.png')

In [ ]:
plt.imshow(X[i])
plt.show()

In [ ]:
cv2.imwrite('test.png',Y[i])

In [82]:
from glob import glob

In [ ]:
save_imgs(Xtrain,Ytrain,path_to_save='/home/ikilbas/USA (Danil country)/cut_set_256/')

In [83]:
lbl_names = glob('/mnt/data/med_data/balanced_batches/batch_1/train_set/origin_wo_4_set/masks/*.bmp')

In [84]:
masks = {}
for mask_name in lbl_names:
    masks[mask_name] = cv2.imread(mask_name)[:,:,0]

In [85]:
scanner = HCScanner(masks, 9)

In [86]:
scanner.scan()

In [87]:
scanner.save_info('uniq_hvc.csv', 'masks_hcvg.csv')

Saved!


In [88]:
fd = pd.DataFrame.from_csv('masks_hcvg.csv')

/home/rustam/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: FutureWarning: from_csv is deprecated. Please use read_csv(...) instead. Note that some of the default arguments are different, so please refer to the documentation for from_csv when changing your function calls
  """Entry point for launching an IPython kernel.


In [89]:
fd.head()

hcvg
/mnt/data/med_data/balanced_batches/batch_1/tra...   319
/mnt/data/med_data/balanced_batches/batch_1/tra...   319
/mnt/data/med_data/balanced_batches/batch_1/tra...   319
/mnt/data/med_data/balanced_batches/batch_1/tra...   271
/mnt/data/med_data/balanced_batches/batch_1/tra...   303

In [90]:
for smth in fd.iterrows():
    print(smth[1][0])
    break

319


In [91]:
len(scanner.hcv_groups)

13

In [93]:
len([200,30,10,500,10,40,60,20,10,10,10,10,10])

13

In [92]:
scanner.hcv_groups

{319: 31,
 271: 3,
 303: 1,
 287: 46,
 447: 1,
 351: 4,
 415: 6,
 315: 2,
 431: 1,
 383: 1,
 479: 1,
 31: 1,
 15: 1}

In [94]:
uniq_num = pd.DataFrame.from_csv('uniq_hvc.csv')

/home/rustam/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: FutureWarning: from_csv is deprecated. Please use read_csv(...) instead. Note that some of the default arguments are different, so please refer to the documentation for from_csv when changing your function calls
  """Entry point for launching an IPython kernel.


In [95]:
uniq_num = uniq_num.get_values()

In [96]:
power = []
for i in uniq_num:
    power.append((sum(i), i))

In [97]:
power = sorted(power, key=lambda x: x[0]) 

In [98]:
new_uniq = []

In [99]:
#i will delete 8 vectors
j = 10
delete = []
for part in power:
    new_uniq.append(part)

In [100]:
len(new_uniq)

13

In [101]:
power

[(4, array([1, 1, 1, 1, 0, 0, 0, 0, 0])),
 (5, array([1, 1, 1, 1, 0, 0, 0, 0, 1])),
 (5, array([1, 1, 1, 1, 1, 0, 0, 0, 0])),
 (6, array([1, 1, 1, 1, 0, 1, 0, 0, 1])),
 (6, array([1, 1, 1, 1, 1, 0, 0, 0, 1])),
 (6, array([1, 1, 0, 1, 1, 1, 0, 0, 1])),
 (7, array([1, 1, 1, 1, 1, 1, 0, 0, 1])),
 (7, array([1, 1, 1, 1, 1, 0, 1, 0, 1])),
 (7, array([1, 1, 1, 1, 1, 0, 0, 1, 1])),
 (7, array([1, 1, 1, 1, 0, 1, 0, 1, 1])),
 (8, array([1, 1, 1, 1, 1, 1, 0, 1, 1])),
 (8, array([1, 1, 1, 1, 1, 1, 1, 0, 1])),
 (8, array([1, 1, 1, 1, 1, 0, 1, 1, 1]))]

In [102]:
new_uniq

[(4, array([1, 1, 1, 1, 0, 0, 0, 0, 0])),
 (5, array([1, 1, 1, 1, 0, 0, 0, 0, 1])),
 (5, array([1, 1, 1, 1, 1, 0, 0, 0, 0])),
 (6, array([1, 1, 1, 1, 0, 1, 0, 0, 1])),
 (6, array([1, 1, 1, 1, 1, 0, 0, 0, 1])),
 (6, array([1, 1, 0, 1, 1, 1, 0, 0, 1])),
 (7, array([1, 1, 1, 1, 1, 1, 0, 0, 1])),
 (7, array([1, 1, 1, 1, 1, 0, 1, 0, 1])),
 (7, array([1, 1, 1, 1, 1, 0, 0, 1, 1])),
 (7, array([1, 1, 1, 1, 0, 1, 0, 1, 1])),
 (8, array([1, 1, 1, 1, 1, 1, 0, 1, 1])),
 (8, array([1, 1, 1, 1, 1, 1, 1, 0, 1])),
 (8, array([1, 1, 1, 1, 1, 0, 1, 1, 1]))]

In [103]:
new_uniq = [i[1] for i in new_uniq]

GDBalancer

In [104]:
from makiflow.augmentation.segmentation import GDBalancer

In [164]:
balancer = GDBalancer(hcv_groups=np.array(new_uniq), initial_c=[200,30,10,500,10,40,60,20,10,10,10,10,10], objective='alpha',min_c=10)#'uniq_hvc.csv'

In [165]:
optimizer = tf.train.AdamOptimizer(0.1)

In [166]:
dest_v = np.array([1., 1., 0.95, 1., 0.6, 0.7, 0.3, 0.3, 1.])

In [167]:
sess = tf.Session()

In [168]:
balancer.set_session(sess)

In [246]:
balancer.optimize(dest_v, optimizer)

0.19941896
[[100.]
 [100.]
 [ 93.]
 [100.]
 [ 51.]
 [ 66.]
 [ 19.]
 [ 22.]
 [ 89.]]
0.1979119
[[100.]
 [100.]
 [ 93.]
 [100.]
 [ 51.]
 [ 66.]
 [ 19.]
 [ 22.]
 [ 90.]]


In [247]:
balancer.get_weights()

array([[117.008385],
       [ 10.      ],
       [ 10.      ],
       [408.72086 ],
       [ 49.909622],
       [ 84.908554],
       [111.283485],
       [ 81.26186 ],
       [ 66.85405 ],
       [ 59.042538],
       [ 71.03585 ],
       [ 74.79618 ],
       [ 74.30672 ]], dtype=float32)

In [51]:
balancer.get_percentage()

array([[100.],
       [100.],
       [ 95.],
       [100.],
       [ 74.],
       [ 51.],
       [ 31.],
       [ 39.],
       [ 90.]], dtype=float32)

In [52]:
shit = balancer.get_weights()
shit = shit.reshape(-1)
shit = np.round(shit).astype(np.int32)

In [53]:
shit

array([105, 104, 103, 102, 102, 110, 183, 208, 150, 208, 210, 213, 211],
      dtype=int32)

In [54]:
from makiflow.augmentation.segmentation.balancing.utils import hcv_to_num

In [55]:
config = {}
for i in range(len(shit)):
    config[hcv_to_num(balancer.hcv_groups[i])] = shit[i]

In [56]:
config

{15: 105,
 271: 104,
 31: 103,
 303: 102,
 287: 102,
 315: 110,
 319: 183,
 351: 208,
 415: 150,
 431: 208,
 447: 210,
 383: 213,
 479: 211}

In [57]:
balancer.save_cardinalities('card.csv')

GD2BBuilder

In [58]:
from makiflow.augmentation.segmentation import GD2BBuilder

In [63]:
lbl_names = glob('/mnt/data/med_data/balanced_batches/batch_1/train_set/origin_wo_4_set/masks/*.bmp')

In [64]:
masks = {}
for mask_name in lbl_names:
    masks[mask_name] = mask_name.replace('masks', 'images')


In [65]:
pd.DataFrame.from_dict(masks, orient='index', columns=['image']).to_csv('mi.csv')

In [66]:
builder = GD2BBuilder(
    path_to_balance_config='card.csv',
    path_to_hc_list='masks_hcvg.csv',
    path_to_mi='mi.csv',
    resize=(1024, 1024)
)

/home/rustam/anaconda3/lib/python3.6/site-packages/makiflow/augmentation/segmentation/balancing/gdbb_builder.py:24: FutureWarning: from_csv is deprecated. Please use read_csv(...) instead. Note that some of the default arguments are different, so please refer to the documentation for from_csv when changing your function calls
  self._hc_list = pd.DataFrame.from_csv(path_to_hc_list)
/home/rustam/anaconda3/lib/python3.6/site-packages/makiflow/augmentation/segmentation/balancing/gdbb_builder.py:25: FutureWarning: from_csv is deprecated. Please use read_csv(...) instead. Note that some of the default arguments are different, so please refer to the documentation for from_csv when changing your function calls
  self._balance_c = pd.DataFrame.from_csv(path_to_balance_config)
/home/rustam/anaconda3/lib/python3.6/site-packages/makiflow/augmentation/segmentation/balancing/gdbb_builder.py:34: FutureWarning: from_csv is deprecated. Please use read_csv(...) instead. Note that some of the default ar

Loading masks and images.
Finished.
Group masks and images by their ids.
319 cardinality is 31
271 cardinality is 3
303 cardinality is 1
287 cardinality is 46
447 cardinality is 1
351 cardinality is 4
415 cardinality is 6
315 cardinality is 2
431 cardinality is 1
383 cardinality is 1
479 cardinality is 1
31 cardinality is 1
15 cardinality is 1
Finished.


In [67]:
builder.set_elastic_aug_params((1024, 1024, 3),alpha=700,std=14,noise_invert_scale=7,border_mode='reflect_101')
builder.create_batch('/mnt/data/med_data/balanced_batches/batch_1/train_set/aug_set/set_1k_1024_wo4class_4')

Balancing group 319...
Augmentor updated 5 times.
Finished.
319 ready
Balancing group 271...
Augmentor updated 34 times.
Finished.
271 ready
Balancing group 303...
Augmentor updated 102 times.
Finished.
303 ready
Balancing group 287...
Augmentor updated 2 times.
Finished.
287 ready
Balancing group 447...
Augmentor updated 210 times.
Finished.
447 ready
Balancing group 351...
Augmentor updated 52 times.
Finished.
351 ready
Balancing group 415...
Augmentor updated 25 times.
Finished.
415 ready
Balancing group 315...
Augmentor updated 55 times.
Finished.
315 ready
Balancing group 431...
Augmentor updated 208 times.
Finished.
431 ready
Balancing group 383...
Augmentor updated 213 times.
Finished.
383 ready
Balancing group 479...
Augmentor updated 211 times.
Finished.
479 ready
Balancing group 31...
Augmentor updated 103 times.
Finished.
31 ready
Balancing group 15...
Augmentor updated 105 times.
Finished.
15 ready


In [3]:
test = glob.glob('/mnt/data/med_data/balanced_batches/paper_batch_1/train_set/orig_set_wo_4/masks/*.bmp')
lbls = []
for mask_name in test:
    lbls += [cv2.imread(mask_name)]

In [69]:
import seaborn as sb
import matplotlib.pyplot as plt

In [ ]:
plt.imshow(lbls[44])
plt.show()

In [4]:
import math
def get_CR_vector(lbls,count_classes):
  uniq = dict([(str(i),0) for i in range(count_classes)])
  
  for i in range(len(lbls)):
    a,b = np.unique(lbls[i], return_counts=True)
    for num in a:
        uniq[str(num)] += 1
  print(uniq)
  return [round(uniq[k] / len(lbls),2) for k in uniq]
  

In [5]:
get_CR_vector(lbls,9)

{'0': 654, '1': 651, '2': 641, '3': 654, '4': 608, '5': 239, '6': 106, '7': 130, '8': 634}


[1.0, 1.0, 0.98, 1.0, 0.93, 0.37, 0.16, 0.2, 0.97]

In [ ]:
len(lbls)

In [ ]:
import seaborn as sns

In [ ]:
sns.heatmap(Ytrain[0])

In [ ]:
cv2.imwrite('2.bmp', test)

In [ ]:
x=cv2.imread('/mnt/data/med_data/balanced_batches/bb_danil1/masks/527_0.bmp')

In [ ]:
sns.heatmap(x)

In [ ]:
test = cv2.resize(x, (1024,1024), interpolation=cv2.INTER_NEAREST)

In [ ]:
b = [] 
for name in a:
    if 'activation' in name:
        continue
    else:
        b.append(str(name))

In [ ]:
b

In [ ]:
"23"