In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.DataFrame.from_csv('contest_data.csv')

C:\Users\Shoto\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: from_csv is deprecated. Please use read_csv(...) instead. Note that some of the default arguments are different, so please refer to the documentation for from_csv when changing your function calls
  """Entry point for launching an IPython kernel.


In [3]:
arr = df.to_numpy()

In [4]:
arr

array([[1, 1, 1, 1, 0, 1, 1, 0, 0, 1],
       [1, 1, 1, 1, 0, 1, 0, 0, 0, 1],
       [1, 1, 1, 1, 0, 1, 1, 0, 0, 1],
       [1, 1, 1, 1, 0, 1, 0, 0, 0, 1],
       [1, 1, 1, 1, 0, 1, 0, 0, 1, 1],
       [1, 1, 1, 1, 0, 1, 0, 0, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 0, 1, 1],
       [1, 1, 1, 1, 0, 1, 1, 0, 1, 1],
       [1, 1, 1, 1, 0, 1, 0, 0, 0, 1],
       [1, 1, 1, 1, 0, 1, 0, 0, 0, 1],
       [1, 1, 1, 1, 0, 1, 1, 0, 0, 1],
       [1, 1, 1, 1, 0, 1, 1, 0, 0, 1],
       [1, 1, 1, 1, 0, 1, 1, 0, 0, 1],
       [1, 1, 1, 1, 0, 1, 0, 0, 0, 1],
       [1, 1, 1, 1, 0, 1, 0, 0, 0, 1],
       [1, 1, 1, 1, 0, 1, 1, 0, 0, 1],
       [1, 1, 1, 1, 0, 1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 0, 0, 1],
       [1, 1, 1, 1, 0, 1, 0, 0, 0, 1],
       [1, 1, 1, 1, 0, 1, 0, 0, 0, 1],
       [1, 1, 1, 1, 0, 1, 0, 0, 0, 1],
       [1, 1, 1, 1, 0, 1, 1, 0, 0, 1],
       [1, 1, 1, 1, 0, 1, 0, 0, 0, 1],
       [1, 1, 1, 1, 0, 1, 0, 0, 0, 1],
       [1, 1, 1, 1, 0, 1, 1, 0, 0, 1],
       [1, 1, 1, 1, 0, 1,

In [5]:
def to_num(bin_vec):
    num = 0
    for i in range(len(bin_vec)):
        num += 2**i * bin_vec[i]
    return num

def get_unique(arr):
    uniq = {}
    uniq_vecs = []
    for vec in arr:
        num = to_num(vec)
        uniq[num] = 1 + uniq.get(num, 0)
        if uniq[num] == 1:
            print(vec)
    return uniq

In [6]:
get_unique(arr)

[1 1 1 1 0 1 1 0 0 1]
[1 1 1 1 0 1 0 0 0 1]
[1 1 1 1 0 1 0 0 1 1]
[1 1 1 1 1 1 1 0 1 1]
[1 1 1 1 0 1 1 0 1 1]
[1 1 1 1 1 1 1 0 0 1]
[1 1 1 1 1 1 0 0 0 1]
[1 1 1 1 0 0 0 0 0 0]
[1 1 1 1 1 0 1 0 1 1]
[1 1 1 1 0 1 0 1 0 1]
[1 1 1 1 0 0 0 0 0 1]
[1 1 1 1 1 1 0 0 1 1]
[1 1 1 1 0 1 0 0 0 0]
[1 1 1 1 0 1 1 1 0 1]
[1 1 1 1 0 0 1 0 0 1]
[1 1 1 1 0 1 0 1 1 1]
[1 1 1 1 1 0 0 0 0 1]


{623: 28,
 559: 33,
 815: 6,
 895: 1,
 879: 2,
 639: 2,
 575: 10,
 15: 4,
 863: 1,
 687: 3,
 527: 3,
 831: 1,
 47: 1,
 751: 2,
 591: 1,
 943: 1,
 543: 1}

In [7]:
# FIRST STAGE

def first_stage(arr, filter_level):
    percentage = arr.sum(axis=0) / len(arr)
    return percentage < filter_level

# SECOND STAGE 

def to_num(bin_vec):
    num = 0
    for i in range(len(bin_vec)):
        num += 2**i * bin_vec[i]
    return num

def get_unique(arr):
    uniq = {}
    uniq_vecs = []
    for vec in arr:
        num = to_num(vec)
        uniq[num] = 1 + uniq.get(num, 0)
        if uniq[num] == 1:
            uniq_vecs += [vec]
    return np.array(uniq_vecs)

# THIRD STAGE

def dist(v1, v2):
    diff = v1 - v2
    return np.sqrt(diff.dot(diff))

def vec_len(vec):
    return np.sqrt(vec.dot(vec))

def find_farest(main_vec, arr):
    # Normalize main vector in order to constaint its values in the interval [0, 1]
    main_vec_norm = main_vec.sum(axis=0) / len(main_vec)
    farest_vec = arr[0]
    farest_dist = dist(farest_vec, main_vec_norm)
    for vec in arr:
        new_dist = dist(main_vec_norm, vec)
        if vec_len(vec) == 0:
            continue
        if new_dist > farest_dist:
            farest_dist = new_dist
            farest_vec = vec
    return farest_vec

# MAIN ALGORITHM

def algorithm(arr, filter_level=0.9, iterations=10):
    # First stage: Filter
    # Figure out which classes actually to balance
    to_balance = first_stage(arr, filter_level)
    arr = arr[:, to_balance]
    # Second stage: Picking unique vectors
    arr = get_unique(arr)
    print(arr)
    # Third stage: Balancing
    # Use euclidian distance to see how far vectors from each other.
    # Add together the most different vectors.
    main_vec = np.zeros(arr.shape[1])
    for i in range(10):
        print(find_farest(main_vec, arr))
        main_vec += find_farest(main_vec, arr)
        
    return main_vec
    

In [8]:
algorithm(arr)

[[0 1 0 0]
 [0 0 0 0]
 [0 0 0 1]
 [1 1 0 1]
 [0 1 0 1]
 [1 1 0 0]
 [1 0 0 0]
 [0 0 1 0]
 [1 0 0 1]
 [0 1 1 0]
 [0 0 1 1]]
[1 1 0 1]
[0 1 0 0]
[0 1 0 0]
[0 1 0 0]
[0 1 0 0]
[0 1 0 0]
[0 1 0 0]
[0 1 0 0]
[0 1 0 0]
[0 1 0 0]


array([ 1., 10.,  0.,  1.])

In [9]:
# FIRST STAGE

def first_stage(arr, filter_level):
    percentage = arr.sum(axis=0) / len(arr)
    return percentage < filter_level

# SECOND STAGE 

def to_num(bin_vec):
    num = 0
    for i in range(len(bin_vec)):
        num += 2**i * bin_vec[i]
    return num

def get_unique(arr):
    uniq = {}
    uniq_vecs = []
    for vec in arr:
        num = to_num(vec)
        uniq[num] = 1 + uniq.get(num, 0)
        if uniq[num] == 1:
            uniq_vecs += [vec]
    return np.array(uniq_vecs), uniq

# THIRD STAGE

def dist(v1, v2):
    diff = v1 - v2
    return np.sqrt(diff.dot(diff))

def vec_len(vec):
    return np.sqrt(vec.dot(vec))

def find_best_candidate(main_vec, arr):
    prevalent = main_vec.max()
    hyper_pyramid = np.ones(len(main_vec)) * (prevalent + 1)
    best_c = arr[0]
    best_dist = dist(hyper_pyramid, arr[0] + main_vec)
    for vec in arr:
        new_dist = dist(hyper_pyramid, vec + main_vec)
        #print(new_dist)
        if new_dist < best_dist:
            best_dist = new_dist
            best_c = vec
    return best_c

# MAIN ALGORITHM

def algorithm(arr, filter_level=0.9, iterations=10):
    # First stage: Filter
    # Figure out which classes actually to balance
    to_balance = first_stage(arr, filter_level)
    arr = arr[:, to_balance]
    # Second stage: Picking unique vectors
    arr, uniq = get_unique(arr)
    print(uniq)
    # Third stage: Balancing
    # Use euclidian distance to see how far vectors from each other.
    # Add together the most different vectors.
    new_uniq = {}
    main_vec = np.zeros(arr.shape[1])
    for i in range(iterations):
        num = to_num(find_best_candidate(main_vec, arr))
        new_uniq[num] = 1 + new_uniq.get(num, 0)
        #print(find_best_candidate(main_vec, arr))
        main_vec += find_best_candidate(main_vec, arr)
        
    return main_vec / iterations, new_uniq
    

In [10]:
algorithm(arr, filter_level=1.1, iterations=1000)

{623: 28, 559: 33, 815: 6, 895: 1, 879: 2, 639: 2, 575: 10, 15: 4, 863: 1, 687: 3, 527: 3, 831: 1, 47: 1, 751: 2, 591: 1, 943: 1, 543: 1}


(array([1. , 1. , 1. , 1. , 0.6, 1. , 0.8, 0.4, 0.8, 1. ]),
 {895: 600, 751: 200, 943: 200})

In [ ]:
def find_best_candidate(main_vec, arr):
    prevalent = main_vec.max()
    hyper_pyramid = np.ones(len(main_vec)) * (prevalent + 1)
    best_c = arr[0]
    best_dist = dist(hyper_pyramid, arr[0] + main_vec)
    for vec in arr:
        new_dist = dist(hyper_pyramid, vec + main_vec)
        #print(new_dist)
        if new_dist < best_dist:
            best_dist = new_dist
            best_c = vec
    return best_c

# MAIN ALGORITHM

def algorithm(arr, filter_level=0.9, iterations=10):
    # First stage: Filter
    # Figure out which classes actually to balance
    to_balance = first_stage(arr, filter_level)
    arr = arr[:, to_balance]
    # Second stage: Picking unique vectors
    arr, uniq = get_unique(arr)
    print(uniq)
    # Third stage: Balancing
    # Use euclidian distance to see how far vectors from each other.
    # Add together the most different vectors.
    new_uniq = {}
    main_vec = np.zeros(arr.shape[1])
    for i in range(iterations):
        num = to_num(find_best_candidate(main_vec, arr))
        new_uniq[num] = 1 + new_uniq.get(num, 0)
        #print(find_best_candidate(main_vec, arr))
        main_vec += find_best_candidate(main_vec, arr)
        
    return main_vec / iterations, new_uniq