In [1]:
import numpy as np
import tensorflow as tf
import pandas as pd
from utils import get_unique

In [2]:
def load_arr():
    df = pd.DataFrame.from_csv('contest_data.csv')
    return df.to_numpy()

In [3]:
data = load_arr()

C:\Users\Shoto\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: FutureWarning: from_csv is deprecated. Please use read_csv(...) instead. Note that some of the default arguments are different, so please refer to the documentation for from_csv when changing your function calls
  


In [4]:
data

array([[1, 1, 1, 1, 0, 1, 1, 0, 0, 1],
       [1, 1, 1, 1, 0, 1, 0, 0, 0, 1],
       [1, 1, 1, 1, 0, 1, 1, 0, 0, 1],
       [1, 1, 1, 1, 0, 1, 0, 0, 0, 1],
       [1, 1, 1, 1, 0, 1, 0, 0, 1, 1],
       [1, 1, 1, 1, 0, 1, 0, 0, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 0, 1, 1],
       [1, 1, 1, 1, 0, 1, 1, 0, 1, 1],
       [1, 1, 1, 1, 0, 1, 0, 0, 0, 1],
       [1, 1, 1, 1, 0, 1, 0, 0, 0, 1],
       [1, 1, 1, 1, 0, 1, 1, 0, 0, 1],
       [1, 1, 1, 1, 0, 1, 1, 0, 0, 1],
       [1, 1, 1, 1, 0, 1, 1, 0, 0, 1],
       [1, 1, 1, 1, 0, 1, 0, 0, 0, 1],
       [1, 1, 1, 1, 0, 1, 0, 0, 0, 1],
       [1, 1, 1, 1, 0, 1, 1, 0, 0, 1],
       [1, 1, 1, 1, 0, 1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 0, 0, 1],
       [1, 1, 1, 1, 0, 1, 0, 0, 0, 1],
       [1, 1, 1, 1, 0, 1, 0, 0, 0, 1],
       [1, 1, 1, 1, 0, 1, 0, 0, 0, 1],
       [1, 1, 1, 1, 0, 1, 1, 0, 0, 1],
       [1, 1, 1, 1, 0, 1, 0, 0, 0, 1],
       [1, 1, 1, 1, 0, 1, 0, 0, 0, 1],
       [1, 1, 1, 1, 0, 1, 1, 0, 0, 1],
       [1, 1, 1, 1, 0, 1,

In [5]:
arr, uniq = get_unique(data)
arr

array([[1, 1, 1, 1, 0, 1, 1, 0, 0, 1],
       [1, 1, 1, 1, 0, 1, 0, 0, 0, 1],
       [1, 1, 1, 1, 0, 1, 0, 0, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 0, 1, 1],
       [1, 1, 1, 1, 0, 1, 1, 0, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 0, 0, 1],
       [1, 1, 1, 1, 1, 1, 0, 0, 0, 1],
       [1, 1, 1, 1, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 0, 1, 0, 1, 1],
       [1, 1, 1, 1, 0, 1, 0, 1, 0, 1],
       [1, 1, 1, 1, 0, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1, 0, 0, 1, 1],
       [1, 1, 1, 1, 0, 1, 0, 0, 0, 0],
       [1, 1, 1, 1, 0, 1, 1, 1, 0, 1],
       [1, 1, 1, 1, 0, 0, 1, 0, 0, 1],
       [1, 1, 1, 1, 0, 1, 0, 1, 1, 1],
       [1, 1, 1, 1, 1, 0, 0, 0, 0, 1]], dtype=int64)

In [5]:
to_balance = arr[:, 4:]
to_balance

array([[0, 1, 1, 0, 0, 1],
       [0, 1, 0, 0, 0, 1],
       [0, 1, 0, 0, 1, 1],
       [1, 1, 1, 0, 1, 1],
       [0, 1, 1, 0, 1, 1],
       [1, 1, 1, 0, 0, 1],
       [1, 1, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 1],
       [0, 1, 0, 1, 0, 1],
       [0, 0, 0, 0, 0, 1],
       [1, 1, 0, 0, 1, 1],
       [0, 1, 0, 0, 0, 0],
       [0, 1, 1, 1, 0, 1],
       [0, 0, 1, 0, 0, 1],
       [0, 1, 0, 1, 1, 1],
       [1, 0, 0, 0, 0, 1]], dtype=int64)

In [6]:
def vec_len(vec):
    vec2 = vec * vec
    vec_sum = tf.reduce_sum(vec2)
    return tf.sqrt(vec_sum)


def distance(vec1, vec2):
    diff = vec1 - vec2
    return vec_len(diff)


def normalize(vec):
    vec_l = vec_len(vec)
    return vec / vec_l

In [7]:
vecs = tf.constant(to_balance.T, dtype=tf.float32)

In [8]:
vecs.shape

TensorShape([Dimension(6), Dimension(17)])

In [9]:
w = np.ones((len(to_balance), 1)) * 100.0
weights = tf.Variable(w, trainable=True, dtype=tf.float32)

In [10]:
weights_clip = tf.clip_by_value(weights, clip_value_min=5.0, clip_value_max=10000.0)

In [11]:
clip = tf.assign(weights, weights_clip)
with tf.control_dependencies([clip]):
    scaled_vecs = tf.matmul(vecs, weights)

In [12]:
normalized_scaled_vecs =  scaled_vecs / tf.reduce_sum(weights)

In [13]:
destination_v = tf.placeholder(dtype=tf.float32, shape=[6, 1])

In [14]:
dist = distance(destination_v, normalized_scaled_vecs)

In [15]:
dist.shape

TensorShape([])

In [16]:
opt = tf.train.AdamOptimizer(100)

In [17]:
train_op = opt.minimize(dist,var_list=[weights] )

In [18]:
sess = tf.Session()

In [19]:
sess.run(tf.global_variables_initializer())

In [20]:
dest = np.array([0.5, 0.5, 0.5, 0.5, 0.5, 0.9]).reshape(6, 1)

In [21]:
for i in range(10):
    _, d = sess.run([train_op, dist], 
            feed_dict={destination_v: dest}
            )
    if i % 20 == 0:
        print(d)
        
np.round(sess.run(scaled_vecs / tf.reduce_sum(weights)), decimals=2) * 100

0.4454305


array([[47.],
       [55.],
       [48.],
       [39.],
       [51.],
       [97.]], dtype=float32)

In [22]:
sess.run(normalized_scaled_vecs)

array([[0.4356189 ],
       [0.5098289 ],
       [0.4461415 ],
       [0.3645156 ],
       [0.47502616],
       [0.9059003 ]], dtype=float32)

In [23]:
sess.run(weights)

array([[  5.      ],
       [  5.      ],
       [  5.      ],
       [362.24054 ],
       [  5.      ],
       [  5.      ],
       [  5.      ],
       [406.79236 ],
       [949.2571  ],
       [442.7358  ],
       [106.196465],
       [282.82584 ],
       [ 86.13213 ],
       [582.69745 ],
       [427.8389  ],
       [884.01764 ],
       [677.58966 ]], dtype=float32)

In [24]:
sess.run(tf.reduce_sum(weights))

5238.324

In [25]:
opt.variables()

[<tf.Variable 'Variable/Adam:0' shape=(17, 1) dtype=float32_ref>,
 <tf.Variable 'Variable/Adam_1:0' shape=(17, 1) dtype=float32_ref>,
 <tf.Variable 'beta1_power:0' shape=() dtype=float32_ref>,
 <tf.Variable 'beta2_power:0' shape=() dtype=float32_ref>]

In [26]:
sess.run(tf.gradients(dist, [weights]),feed_dict={destination_v: dest})

[array([[ 7.65324730e-05],
        [ 1.40104996e-04],
        [ 1.10626825e-04],
        [-2.89387244e-05],
        [ 4.70542873e-05],
        [ 5.39454049e-07],
        [ 6.41119841e-05],
        [ 1.21538789e-04],
        [-4.05404280e-05],
        [-1.98156922e-05],
        [ 1.28503307e-04],
        [ 3.46338056e-05],
        [ 1.33140478e-04],
        [-8.33882223e-05],
        [ 6.49307767e-05],
        [-4.92938707e-05],
        [ 5.25102878e-05]], dtype=float32)]

In [27]:
from gd_balancer import GDBalancer

In [35]:
b = GDBalancer(
    tf.train.AdamOptimizer(.1),
    to_balance=arr,
    objective='alpha',
    min_amount=50,
    initial_amount=1000)

In [36]:
d = np.array([1.0, 1.0, 1.0, 1.0, 0.5, 0.5, 0.5, 0.6, 0.5, 0.9]).reshape(10, 1)

In [116]:
b.optimize(d, iterations=100, print_period=50)

0.36608744
[[100.]
 [100.]
 [100.]
 [100.]
 [ 40.]
 [ 67.]
 [ 45.]
 [ 31.]
 [ 41.]
 [ 93.]]
0.36415106
[[100.]
 [100.]
 [100.]
 [100.]
 [ 40.]
 [ 67.]
 [ 45.]
 [ 32.]
 [ 41.]
 [ 93.]]


### The answer of the algorithm

In [119]:
b.get_percentage().reshape(-1)

array([100., 100., 100., 100.,  40.,  67.,  45.,  32.,  41.,  93.],
      dtype=float32)

### Original data

In [32]:
(data.sum(axis=0) / data.shape[0]) * 100

array([100., 100., 100., 100.,  16.,  90.,  37.,   6.,  12.,  95.])

### Total number of pictures

In [120]:
b.get_vec_num()

13916.6045

### How many of different pictures is used

In [121]:
b.get_weights()

array([[ 457.55325],
       [ 467.58725],
       [ 448.69424],
       [1316.3212 ],
       [ 403.0307 ],
       [ 404.55615],
       [ 449.7555 ],
       [ 498.22232],
       [1496.0441 ],
       [1451.0895 ],
       [ 453.9523 ],
       [ 512.4514 ],
       [ 479.54056],
       [1474.5013 ],
       [ 672.3092 ],
       [1484.9897 ],
       [1446.0055 ]], dtype=float32)

In [34]:
b.reset(800,tf.train.MomentumOptimizer(100, 0.9), objective='alpha')